powerdata <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE)
plotdata <- subset(powerdata, Date=="1/2/2007" | Date=="2/2/2007")
png(filename="plot1.png")
hist(as.numeric(plotdata$Global_active_power), col="red", xlab="Global Active Power(kilowatts)", main="Global Active Power")
dev.off()
